### ISSUE TITLE
Hacker is not given hacker rolebinding after account confirmation

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#330]

**Comment by Jerryzzeder902** [comment]
I almost fell for scam, until I met this my old time friend who is now retired from USA dark web work,she’s highly skilled in all types of hacking and I bet you’re safe with her. Contact her on cryptocyberhacker@gmail.com You just try it and tell the sweet testimony like I am also,I told her I owe her a lot, and I have to pay her by letting people know her good works.
she does all types of hacking according to what she told me, which includes Facebook, Snapchat,mail,Instagram.she also hacks phone, bitcoin address, western union to increase money, and CCTV,also iPhone and Icloud hacking, contact her and I bet,you’ll tell a success story, because she has never failed in all she did for me.
cryptocyberhacker@gmail.com that’s her mail.
