### ISSUE TITLE
Switch CI to Github Actions

### ISSUE THREAD

**Issue by loreina** [hackmcgill/hackerAPI#660]
Switching CI from TravisCI to Github Actions

This'll be done in a few parts: 

- [ ] Move test build to Github Actions and remove TravisCI integration
- [ ] Checks for formatting and linting
- [ ] Add seed script to CI in the future when we have our API refactored (dup: #653)

For CD, we currently deploy to Heroku on push to `master`. Let's revisit after the refactor to see if if we prefer triggering Heroku deployment in Github Actions (a proxy to something that doesn't really have to be changed but nice to have everything in one place? hella extra tho)

**Comment by krubenok** [comment]
> Let's revisit after the refactor to see if if we prefer triggering Heroku deployment in Github Actions (a proxy to something that doesn't really have to be changed but nice to have everything in one place? hella extra tho)

I think this is a good idea since we can then control this to only happen after certain other things have happened in Github Actions (like `npm run seed`). 

@pierreTklein and I were also texting this morning about an interesting idea for how to handle Docs. Attaching screenshot: 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/2529120/89077145-65edcf00-d336-11ea-8099-c0885b660164.png">

This would basically make having correct Docs a Github actions powered test case. If you want this broken out into a different but related issue 👍 . There would also be the potential to do branch deploys of the docs on Vercel/Netlify which would be yet another likely separate but related issue.

**Comment by krubenok** [comment]
Also for linting: https://github.com/github/super-linter
